name = "test_project"
is_library = false
version = "0.0.1"
build_path = "out"
additional_linking_material = []

# remote_compiler_workers = [
#     { name = "Remote", address = "[::1]:3030" },
# ]

[dependencies]
# dependency-test = { version = "0.0.1", remote = "Remote", features = [] }