[package]
name = "dependency-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../language/common"}
dioxus = "0.7.1"
r2d2 = "0.8.10"
env_logger = "0.11.8"
serde = "1.0.228"
rand = "0.9.2"
base64 = "0.22.1"
diesel = {version = "2.3.4", features = ["extras", "postgres"]}
