name = "config_test"
is_library = false
version = "0.0.1"
build_path = "out"
additional_linking_material = []

[[remote_compiler_worker]]
name = "Test1"
address = "[::1]:3003"

[[remote_compiler_worker]]
name = "Test2"
address = "[::1]:3004"

[dependencies]
dep1 = { version = "0.0.1", features = ["hello"], remote = "Test1"}